name: saison13
services:

  keycloak:
      ports:
          - 8080:8080
      environment:
          - KC_BOOTSTRAP_ADMIN_USERNAME=admin
          - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      image: quay.io/keycloak/keycloak:26.1.4
      command: start-dev
      
  postgres_mtt:
      image: postgres:${POSTGRES_IMAGE_TAG}
      restart: ${RESTART_POLICY}
      security_opt:
        - no-new-privileges:true
      pids_limit: 100
      read_only: true
      tmpfs:
        - /tmp
        - /var/run/postgresql
      volumes:
        - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
      environment:
        # timezone inside container
        - TZ

        # necessary Postgres options/variables
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB

  mattermost:
    depends_on:
      - postgres_mtt
    image: mattermost/${MATTERMOST_IMAGE}:${MATTERMOST_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    read_only: ${MATTERMOST_CONTAINER_READONLY}
    tmpfs:
      - /tmp
    volumes:
      - ${MATTERMOST_CONFIG_PATH}:/mattermost/config:rw
      - ${MATTERMOST_DATA_PATH}:/mattermost/data:rw
      - ${MATTERMOST_LOGS_PATH}:/mattermost/logs:rw
      - ${MATTERMOST_PLUGINS_PATH}:/mattermost/plugins:rw
      - ${MATTERMOST_CLIENT_PLUGINS_PATH}:/mattermost/client/plugins:rw
      - ${MATTERMOST_BLEVE_INDEXES_PATH}:/mattermost/bleve-indexes:rw

    environment:
      # timezone inside container
      - TZ

      # necessary Mattermost options/variables (see env.example)
      - MM_SQLSETTINGS_DRIVERNAME
      - MM_SQLSETTINGS_DATASOURCE

      # necessary for bleve
      - MM_BLEVESETTINGS_INDEXDIR

      # additional settings
      - MM_SERVICESETTINGS_SITEURL
    ports:
      - ${APP_PORT}:8065
      - ${CALLS_PORT}:${CALLS_PORT}/udp
      - ${CALLS_PORT}:${CALLS_PORT}/tcp


  kotaemon:
      environment:
          - GRADIO_SERVER_NAME=0.0.0.0
          - GRADIO_SERVER_PORT=7860
      volumes:
          - ./ktem_app_data:/app/ktem_app_data
      ports:
          - 7860:7860
      stdin_open: true
      tty: true
      image: ghcr.io/cinnamon/kotaemon:main-lite

  moodleapp:
      ports:
          - 8100:443
      image: moodlehq/moodleapp